---
title: "Bike share_Mechine learning: linear regression"
output: html_notebook
Author: Zhuangfang Yi. https://geoyi.org
---

```{r}
setwd("...")
list.files("...")
df <- read.csv("bikeshare.csv", sep = ",")
head(df, 4)
```

```{r}
library(ggplot2)
library(ggthemes)
library(dplyr)
library(corrgram)
library(plotly)
Sys.setenv("plotly_username"="geospatialanalystyi")
Sys.setenv("plotly_api_key"="kavplmotix")
Sys.setenv("plotly_domain"="https://plotly.your-company.com")

#check out the correlation between variables
#Bike.Num <- sapply(df, is.numeric)
#Bike.cor <- cor(df[,Bike.Num])
#corrplot::corrplot(Bike.cor, method = "color")
p1 <- corrgram(df, order = TRUE, lower.panel = panel.shade, upper.panel = panel.pie, text.panel = panel.txt)
plotly::plotly(p1)
```

```{r}
ggplot(df, aes(x=temp, y=count)) + geom_point(aes(colour = temp),alpha=0.5) 
```
```{r}
#covert date "2013-03-11 07:00" to POSIXct format "2013-03" 
df$datetime <- as.POSIXct(df$datetime)
ggplot(df, aes(x=datetime, y=count)) + geom_point(aes(colour=temp),alpha=0.5,position=position_jitter(w=2, h=0)) + scale_color_continuous(low='#55D8CE',high='#FF6E2E') 
```
```{r}
col.tem.count <- cor(df[,c('temp', 'count')])
col.tem.count
```
```{r}
ggplot(df, aes(x=factor(season), y=count)) + geom_boxplot(aes(colour=factor(season)))
```
```{r}
df$hour <- format(df$datetime,"%H")
head(df)
```

```{r}
workday.bike <- df %>%
  filter(workingday == 1)
#color selection was from http://www.color-hex.com/color-wheel/, I use color 1 combination.
ggplot(workday.bike, aes(x=hour, y=count)) + geom_point(aes(color=temp),position=position_jitter(w=1.5, h=0.5), alpha=0.5) + scale_color_gradientn(colors = c("#161c64","#1827e2",'#983cec','#ad3cec', '#ea3cec','#ec3c6c','#ec613c','#ec863c','#eca33c','#ecd13c'))
```
```{r}
NotWork.day <- df %>%
  filter(workingday == 0)
ggplot(NotWork.day, aes(x=hour, y=count)) + geom_point(aes(color=temp),position=position_jitter(w=1.5, h=0.5), alpha=0.5) + scale_color_gradientn(colors = c("#161c64","#1827e2",'#983cec','#ad3cec', '#ea3cec','#ec3c6c','#ec613c','#ec863c','#eca33c','#ecd13c'))
```
```{r}
temp.model <- lm(count ~ temp, data = df)
summary(temp.model)
```
```{r}
#make prediction using the linear regression model
print("How many bikes do we need when the temprature is 30?")
temp.test <- data.frame(temp=30)
predict(temp.model,temp.test)
```
```{r}
df$hour <- sapply(df$hour, as.numeric)
P.bike <- select(df, season : hour)
#bike.num <- lapply(P.bike, as.numeric)
str(bike.num)
```

```{r}
bike.model <- lm(count ~., data =bike.num)
summary(bike.model)
```
###At this poit we could make a prediction/assuption: Today, it's summer time, and holiday; the weather is  clear, few clouds; temp is 25; but air temp is about 28; humidity is about 70%; weedspeed is about 10; and it's close to 10am now. So we could predict how many bikes are needed for the specific hour, day and weather. 

```{r}
bike.test <- data.frame(season=3, holiday =1, workingday = 0, weather = 1, temp=25, atemp = 28, humidity = 70.0, windspeed = 10.0, hour = 10, casual =11, registered = 140)
predict(bike.model, bike.test)
```
```{r}

```

